site_name: Documentation of the L2 Python architecture
theme:
  name: readthedocs
  highlightjs: true
  collapse_navigation: False
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          paths: [L2/l2]
          options:
            docstring_style: google
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

